module.exports = {
  data: [ { name: { first: 'Kenny', last: 'Rosenberg' },
    hours: { totalTime: 5.75, billableTime: 5.5 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Tyler', last: 'Shambora' },
    hours: { totalTime: 7.279999999999999, billableTime: 0 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Cory', last: 'Cummings' },
    hours: { totalTime: 7.43, billableTime: 2.5199999999999996 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Daniel', last: 'Lerman' },
    hours: { totalTime: 8, billableTime: 4.75 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Ryan', last: 'Little' },
    hours: { totalTime: 8, billableTime: 6.25 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Jacob', last: 'Tooman' },
    hours: { totalTime: 7, billableTime: 4 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Kris', last: 'Johnson' },
    hours: { totalTime: 8, billableTime: 0 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Jason', last: 'Redick' },
    hours: { totalTime: 8, billableTime: 4.5 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Adrian', last: 'Nuyda' },
    hours: { totalTime: 7.16, billableTime: 6.66 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Lynwhel', last: 'Claricia' },
    hours: { totalTime: 8, billableTime: 6.25 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Steph', last: 'Brock' },
    hours: { totalTime: 8, billableTime: 3 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Jessica', last: 'Pond' },
    hours: { totalTime: 8, billableTime: 0 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Sam', last: 'Webb' },
    hours: { totalTime: 8, billableTime: 6.5 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Aaron', last: 'Markle' },
    hours: { totalTime: 7.25, billableTime: 5.5 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Joe', last: 'Pena' },
    hours: { totalTime: 7, billableTime: 1 },
    active: { is_active: false, is_billable: false } },
  { name: { first: 'Eric', last: 'Jones' },
    hours: { totalTime: 6.5, billableTime: 5 },
    active: { is_active: false, is_billable: false } } ]
};
